CREATE TABLE weather_station_data (
    id                                  SERIAL                          PRIMARY KEY,
    timestamp                           TIMESTAMP WITHOUT TIME ZONE     NOT NULL,
    flow_in_l_per_s                     NUMERIC(10, 2),
    reservoir_level_percent             NUMERIC(5, 2),
    pressure_mca                        NUMERIC(10, 2),
    gmb_1_is_on                         BOOLEAN,
    gmb_2_is_on                         BOOLEAN,
    total_precip_mm                     NUMERIC(10, 2),
    station_pressure_mb                 NUMERIC(10, 2),
    max_pressure_last_hour_mb           NUMERIC(10, 2),
    min_pressure_last_hour_mb           NUMERIC(10, 2),
    global_radiation_kj_per_m2          NUMERIC(10, 2),
    air_temp_c                          NUMERIC(5, 2),
    dew_point_temp_c                    NUMERIC(5, 2),
    max_temp_last_hour_c                NUMERIC(5, 2),
    min_temp_last_hour_c                NUMERIC(5, 2),
    max_dew_point_last_hour_c           NUMERIC(5, 2),
    min_dew_point_last_hour_c           NUMERIC(5, 2),
    max_humidity_last_hour_percent      NUMERIC(5, 2),
    min_humidity_last_hour_percent      NUMERIC(5, 2),
    relative_humidity_percent           NUMERIC(5, 2),
    wind_direction_deg                  NUMERIC(5, 2),
    max_wind_gust_m_per_s               NUMERIC(5, 2),
    wind_speed_m_per_s                  NUMERIC(5, 2)
);